### ISSUE TITLE
Combinatorial example error: delt_idx not defined

### ISSUE THREAD

**Issue by federicodassereto** [HazyResearch/hyperbolics#11]
I'm trying the example proposed in the README, but I'm having some trouble with the comb.jl file.

While running the command:
`julia combinatorial/comb.jl -d data/edges/phylo_tree.edges -m phylo_tree.r10.emb -e 1.0 -p 64 -r 10 -a -s`

with the dimension parameter greater than 2, I have the following error:
`ERROR: LoadError: UndefVarError: delt_idx not defined`

which is originated in the rdim.jl file, at the 249th line, in function place_on_sphere().
It seems that in such function the variable "is forgotten" when the points_idx parameter is increased.
When the dimension is set to 2, the embedding is successfully created with all the measurements completed.
I'm running Julia 0.7.

Thank You in advance.

**Comment by fredsala** [comment]
This is almost certainly an init bug, and initializing delt_idx = delta outside the loop will fix it.
