### ISSUE TITLE
Embeddings extraction from PyTorch model.

### ISSUE THREAD

**Issue by ibalejandro** [HazyResearch/hyperbolics#14]
Thank you for this awesome project!

I am trying to use your PyTorch implementation in order to train a model and extract the embedding matrix from it. As a result, I am getting values that are not between 0 and 1, as it is supposed to be for hyperbolic embeddings, but I am not sure whether it is normal or I need to do some post-processing in order to get the right embeddings.

The way I'm trying to extract the matrix from the model is the following:

 device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
 model = torch.load(model_load_file).to(device)
 embedding_flatten = model.embedding().data
 embedding_dim = (embedding_flatten.shape[0] // model.n)
 num_nodes = model.n
 embedding_matrix = embedding_flatten.view(num_nodes, embedding_dim)

Any help would be much appreciated. Thanks in advance!

**Comment by albertfgu** [comment]
The current code uses the hyperboloid model instead of the Poincare model (see https://openreview.net/pdf?id=HJxeWnCcF7), which does not limit points to the unit ball. If you would like to use the Poincare model instead, see lines 92-93 of hyperbolic_models.py.

**Comment by ibalejandro** [comment]
Thank you @albertfgu for the useful answer! As I see, it is just a matter of uncommenting line 92 and uncommenting line 93 on the file you mentioned.
