### ISSUE TITLE
--use-svrg doesn't work

### ISSUE THREAD

**Issue by rsonthal** [HazyResearch/hyperbolics#16]
So I tried using the --use-svrg command and it didn't work. 

First it told me I could Hyperbolic_Parameter from hyperbolic_parameter.  I changed this so that it imports HyperbloidParameter instead. So that line went fine until we got to line 94 of svrg.py file where I get the following error

```

File "/hyperbolics-master/pytorch/svrg.py", line 94, in step
    for i, (data, target) in enumerate(self.data_loader):
ValueError: too many values to unpack (expected 2)

```

I was wondering if there was a quick fix for this.

**Comment by macio232** [comment]
You need to rewrite the `use_svrg` section https://github.com/HazyResearch/hyperbolics/blob/20d59119ccfde7f37fc18d2d5c2fc0a81eda6846/pytorch/pytorch_hyperbolic.py#L480-L490 into the following form
```python
        if use_svrg:
            for data in z:
                def closure(data=data, target=None):
                    _data = data if target is None else (data,target)
                    c = m.loss(cu_var(_data))
                    c.backward()
                    return c.item()
                l += opt.step(closure)
                n_edges += data[0].size(0)

                # Projection
                m.normalize()
```
and https://github.com/HazyResearch/hyperbolics/blob/20d59119ccfde7f37fc18d2d5c2fc0a81eda6846/pytorch/svrg.py#L94-L95
into
```python
            for i, data in enumerate(self.data_loader):
                closure(data)
```
However, even with such a fix, I had problems with numerical issues. But this could be data-dependent. Good luck!

**Comment by rsonthal** [comment]
Thank you for the fix! Yes I am also having numerical issues. I think I will stick to not using surge

**Comment by albertfgu** [comment]
Hi, apologies for the issues and thanks for the fix @macio232. The SVRG code was indeed an outdated option for earlier versions of the code and was not used for any of our final experiments.
