### ISSUE TITLE
Julia Version Problems 

### ISSUE THREAD

**Issue by davecerr** [HazyResearch/hyperbolics#18]
Hello,

What version of Julia do I need to run comb.jl? It seems like a lot of the commands are now outdated.

Thanks

**Comment by davecerr** [comment]
Managed to fix.

**Comment by gcorso** [comment]
@davecerr how did you fix?

**Comment by juice500ml** [comment]
@gcorso It seems to be fixed in https://github.com/HazyResearch/hyperbolics/pull/17, whereas it's still not merged.
