### ISSUE TITLE
Example of embedding non-tree graph

### ISSUE THREAD

**Issue by bkj** [HazyResearch/hyperbolics#7]
Do you have any examples of running your algorithm on non-tree graphs?  From the paper, it sounds like sometimes you use a Steiner tree and sometimes a BFS tree -- are you able to give some details on how you got the reported numbers for the `diseases`, `Gr-QC` and `wordnet` datasets?

Thanks!

**Comment by albertfgu** [comment]
The reported numbers should be reproducible using the current combinatorial construction code, which uses a BFS tree by default. Although the main combinatorial construction requires a tree, this preprocessing is done automatically in `comb.jl`, so any graph can be passed in without issue.
The other methods such as hMDS and the PyTorch optimization embeddings are for generic graphs.

**Comment by bkj** [comment]
Fantastic -- thanks!
