### ISSUE TITLE
wrong Embedding dimensions 

### ISSUE THREAD

**Issue by xionghc** [HazyResearch/hyperbolics#9]
when dim was set to 2, actually the dims of embeddings is 3, and --visualize doesn't work. But set the dim to 1, and the dimension become 2, Visualisation can work, but the graph was totally wrong. 

I just use the example command line in README file. What wrong with the code?

**Comment by fredsala** [comment]
We’ve extended visualization to support the hyperboloid model (dim=2) and spherical (dim=1, the circle, and dim=2, the sphere), along with products of multiple hyperbolic/spherical spaces.

You should be able to run 

python pytorch/pytorch_hyperbolic.py learn data/edges/smalltree.edges --batch-size 64 -l 5.0 --epochs 1000 --checkpoint-freq 10 --resample-freq 5000 --subsample 16 --visualize --hyp 1 --dim 2 --sph 1 --sdim 2
